version: "3.9"
services:
  backendserver:
    build:
      context: ./KCP_Backend_Server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    container_name: kcp_backend
    depends_on:
      - nginx

  jobscraping:
    build:
      context: ./Job_Scraping
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    restart: always
    container_name: job_scraping
    depends_on:
      - nginx

  # resume:
  #   build:
  #     context: ./Resume
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - nginx

  community:
    build:
      context: ./Community
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    restart: always
    container_name: community
    depends_on:
      - nginx

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8085:80"

  grafana:
    image: grafana/grafana
    ports:
      - 8080:8080
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - grafana_network

volumes:
  grafana_data:

networks:
  grafana_network:
